# Generated by Django 5.2 on 2025-04-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_product_image_path_product_nickname_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quentity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
